name: sqljocky
version: 0.14.1
author: James Ots <code@jamesots.com>
description: A MySQL connector
homepage: https://github.com/jamesots/sqljocky
environment:
  sdk: '>=1.11.0 <2.9.0'
documentation: http://jamesots.github.io/sqljocky/docs
dependencies:
  crypto: any
  logging: any
  options_file: any
dev_dependencies:
  test: any
  mockito: any
  args: any
